In [862]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [863]:
tf.reset_default_graph()

In [864]:
source_inputs = [np.random.randint(2,101,n) for n in  np.random.randint(5,11,25)]
target_inputs = [np.random.randint(2,101,n) for n in  np.random.randint(5,11,25)]

print(source_inputs)
print(target_inputs)

[array([57, 45,  5, 68, 33, 68, 18, 95, 45]), array([15, 10, 70, 20, 46, 24]), array([61, 33, 36, 17, 43, 31, 64]), array([25, 59, 18, 61, 57, 72, 80, 84, 48, 17]), array([55, 32, 85,  4, 86]), array([56, 91,  4, 64, 81, 78, 70, 93]), array([57,  2, 94, 63, 59, 77, 42, 15]), array([ 6,  3, 23, 55, 93, 53, 42, 27,  9, 30]), array([48, 70, 24, 42, 14]), array([80, 43, 48,  4, 83, 95]), array([25, 80, 92, 40, 17]), array([20, 53, 55, 24,  4]), array([38, 14, 15, 67, 73, 86, 29,  7,  8]), array([96, 78, 15, 59, 46, 75, 88]), array([23, 59, 35, 22, 35,  9]), array([33, 10, 89, 64, 10, 64, 27, 38]), array([84, 54, 63, 96, 75]), array([50, 27, 15, 21, 67,  5, 14, 18,  3]), array([ 85,   2,  85,  87,  55,  38, 100,  48,  97]), array([42, 37, 14, 30, 61, 21, 12, 65]), array([58, 39, 11, 98, 86, 19, 90, 47, 45, 28]), array([71, 22, 26, 42, 85]), array([23, 86,  6,  7, 55,  4, 77]), array([30, 93, 89, 36, 83, 22, 69]), array([78, 77, 20,  5, 53, 78, 42, 50])]
[array([58, 38, 33, 97, 83, 24, 76]),

In [865]:
source_lens = list(map(len,source_inputs))
target_lens = list(map(len,target_inputs))

print(input_lens, output_lens)

[8, 6, 9, 5, 5, 9, 7, 7, 6, 10] [10, 6, 9, 6, 9, 7, 7, 6, 8, 9]


In [866]:
padded_inputs = np.array([np.concatenate((i,
            [0 for j in range(10-len(i))])) for i in source_inputs])

In [867]:
padded_inputs

array([[  57.,   45.,    5.,   68.,   33.,   68.,   18.,   95.,   45.,
           0.],
       [  15.,   10.,   70.,   20.,   46.,   24.,    0.,    0.,    0.,
           0.],
       [  61.,   33.,   36.,   17.,   43.,   31.,   64.,    0.,    0.,
           0.],
       [  25.,   59.,   18.,   61.,   57.,   72.,   80.,   84.,   48.,
          17.],
       [  55.,   32.,   85.,    4.,   86.,    0.,    0.,    0.,    0.,
           0.],
       [  56.,   91.,    4.,   64.,   81.,   78.,   70.,   93.,    0.,
           0.],
       [  57.,    2.,   94.,   63.,   59.,   77.,   42.,   15.,    0.,
           0.],
       [   6.,    3.,   23.,   55.,   93.,   53.,   42.,   27.,    9.,
          30.],
       [  48.,   70.,   24.,   42.,   14.,    0.,    0.,    0.,    0.,
           0.],
       [  80.,   43.,   48.,    4.,   83.,   95.,    0.,    0.,    0.,
           0.],
       [  25.,   80.,   92.,   40.,   17.,    0.,    0.,    0.,    0.,
           0.],
       [  20.,   53.,   55.,   24.,    4., 

In [868]:
source_mask_array = 1.0*(padded_inputs>0)
source_mask_array

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.

In [869]:
padded_outputs = np.array([np.concatenate((i,
            [0 for j in range(10-len(i))])) for i in target_inputs])
padded_outputs

array([[  58.,   38.,   33.,   97.,   83.,   24.,   76.,    0.,    0.,
           0.],
       [  76.,   26.,   27.,   60.,   19.,   38.,    0.,    0.,    0.,
           0.],
       [  13.,   99.,   95.,   38.,   42.,    4.,   87.,    6.,   89.,
           0.],
       [  99.,   66.,   25.,   99.,   42.,    0.,    0.,    0.,    0.,
           0.],
       [  44.,   94.,    4.,   73.,    4.,   76.,   44.,    5.,   44.,
           0.],
       [   6.,   43.,   72.,   94.,   99.,   53.,   27.,   55.,   63.,
           0.],
       [   6.,   69.,   17.,   22.,   52.,    0.,    0.,    0.,    0.,
           0.],
       [  49.,    9.,   40.,   88.,   94.,   36.,   26.,    0.,    0.,
           0.],
       [  72.,   52.,   84.,   24.,  100.,   59.,   81.,   71.,   57.,
          78.],
       [  25.,   32.,   72.,   52.,   72.,    0.,    0.,    0.,    0.,
           0.],
       [  89.,   74.,  100.,   65.,   54.,   82.,   40.,   30.,   27.,
           0.],
       [  69.,   79.,   32.,   70.,   73., 

In [870]:
target_mask_array = 1.0*(padded_outputs>0)
target_mask_array

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.

In [871]:
batch_size = 3
source_vocab_size = 100
target_vocab_size = 100
embed_size = 20
hidden_size = 25
align_size = 15

In [872]:
source_ids = tf.placeholder(dtype=tf.int32,shape=[None,None])
source_seq_lens = tf.placeholder(dtype=tf.int32,shape=[None])
source_mask = tf.placeholder(dtype=tf.float32,shape=[None,None])

In [873]:
source_embeddings = tf.get_variable('source_embedding_matrix',
                            [source_vocab_size+1, embed_size])
enc_inputs = tf.nn.embedding_lookup(source_embeddings, source_ids)

In [874]:
enc_fw_cell = tf.contrib.rnn.GRUCell(hidden_size)
enc_bw_cell = tf.contrib.rnn.GRUCell(hidden_size)

In [875]:
enc_outputs, states = \
tf.nn.bidirectional_dynamic_rnn(cell_fw = enc_fw_cell, 
                                         cell_bw = enc_bw_cell,
                                         inputs = enc_inputs,
                                         sequence_length = source_seq_lens,
                                         dtype = tf.float32)

In [876]:
concat_enc_outputs = tf.concat(enc_outputs, axis=2)

In [877]:
bw_enc_output1 = enc_outputs[-1][:,1,:]

In [878]:
U = tf.get_variable('U',[hidden_size,hidden_size])

In [879]:
decoder_state = tf.matmul(bw_enc_output1,U)

In [880]:
batch_size = tf.placeholder(tf.int32)

In [881]:
W = tf.get_variable('W',[1,2*hidden_size,align_size],dtype=tf.float32)
W_rep = tf.tile(W,[batch_size,1,1])

In [882]:
X = tf.matmul(concat_enc_outputs,W_rep)

In [883]:
V = tf.get_variable('V',[hidden_size,align_size])

In [884]:
v = tf.get_variable('v',[1,align_size,1])

In [885]:
v_rep = tf.tile(v,[batch_size,1,1])

In [886]:
P = tf.get_variable('P',[hidden_size,target_vocab_size+2])
b = tf.get_variable('b',[target_vocab_size+2])

In [887]:
target_embeddings = tf.get_variable('target_embedding_matrix',
                            [target_vocab_size+2, embed_size])

In [888]:
with tf.variable_scope('RNN'):
    decoder_cell = tf.contrib.rnn.GRUCell(hidden_size)

In [889]:
decoder_embed = tf.nn.embedding_lookup(target_embeddings, 
                                       tf.ones([batch_size],tf.int32))

In [890]:
decoder_output = tf.placeholder(tf.int32,[None,None])

In [891]:
decoder_length = 10

In [892]:
target_mask = tf.placeholder(dtype=tf.float32,shape=[None,None])

In [893]:
target_seq_lens = tf.placeholder(dtype=tf.int32,shape=[None])

In [894]:
total_loss = 0

In [895]:
for t in range(decoder_length):
    with tf.variable_scope('RNN'):
        logits = []
        if t > 0:
            tf.get_variable_scope().reuse_variables()
        r_t = tf.matmul(decoder_state,V)
        
        tanh_input = X + tf.expand_dims(r_t,axis=1)
        u_t = tf.matmul(tanh_input,v_rep)
        u_t = tf.squeeze(u_t,axis=2)

        exp_u_t = tf.exp(u_t)
        softmax_denom = tf.reduce_sum(exp_u_t*source_mask,axis=1,keep_dims=True)
        a_t = exp_u_t/softmax_denom
        a_t = a_t*source_mask

        a_expn = tf.expand_dims(a_t,axis=1)
        c_t = tf.matmul(a_expn,concat_enc_outputs)
        c_t = tf.squeeze(c_t,axis=1)

        decoder_input = tf.concat([decoder_embed,c_t],
                                  axis=1)
        decoder_state,_ = decoder_cell(decoder_input,
                                       decoder_state) 

        logit = tf.nn.xw_plus_b(decoder_state,P,b)
        logits.append(tf.argmax(logit, 1))
        onehot = tf.one_hot(decoder_output[:,t],
                            depth=target_vocab_size+2)
        
        
        cross_entropy = tf.nn.softmax_cross_entropy_with_logits(
                        logits = logit,
                        labels = onehot
                    )
        
        xe_mask = tf.cast(tf.greater(decoder_output[:,t],0),tf.float32)
        
        cross_entropy = xe_mask*cross_entropy
        
        loss = tf.reduce_sum(cross_entropy)
        
        

        total_loss += loss
    
avg_loss = total_loss / tf.reduce_sum(target_mask)
train_op = tf.train.AdamOptimizer(1e-4).minimize(avg_loss)

In [896]:
num_examples = len(padded_inputs)

In [897]:
batch_size_ = 6

In [901]:
start = 0

In [902]:
import math

In [903]:
for i in range(math.ceil(num_examples/batch_size_)):
    start = i*batch_size_
    end = start + batch_size_
    with tf.Session() as sess:
        init_op = tf.global_variables_initializer()
        sess.run(init_op)
        logits_,avg_loss_,_ = sess.run([logits,avg_loss,train_op],
                            feed_dict={
                                       batch_size:min(num_examples, end) - start,
                                       source_mask:source_mask_array[start:end,:],
                                       target_mask:target_mask_array[start:end,:],
                                       source_ids:padded_inputs[start:end], 
                                       source_seq_lens:source_lens[start:end],
                                       target_seq_lens:target_lens[start:end],
                                       decoder_output:padded_outputs[start:end,:],
                                      })
    print(logits_,avg_loss_)

[array([15, 97, 30, 15, 15, 15])] 4.62098
[array([3, 3, 3, 3, 3, 3])] 4.62041
[array([44, 44, 44, 44, 44, 44])] 4.64575
[array([71, 94, 94, 71, 89, 94])] 4.62137
[array([41])] 4.60123
